insert into product (id, name, creation_date) values (1, 'Beef - Short Loin', '2023-08-08');
insert into product (id, name, creation_date) values (2, 'Cranberry Foccacia', '2023-12-21');
insert into product (id, name, creation_date) values (3, 'Cheese - Comtomme', '2023-12-23');
insert into product (id, name, creation_date) values (4, 'Creamers - 10%', '2023-12-10');
insert into product (id, name, creation_date) values (5, 'Wine - Cabernet Sauvignon', '2023-04-16');
insert into product (id, name, creation_date) values (6, 'Soup - Campbells, Lentil', '2024-03-04');
insert into product (id, name, creation_date) values (7, 'Chilli Paste, Sambal Oelek', '2023-09-01');
insert into product (id, name, creation_date) values (8, 'Mix - Cappucino Cocktail', '2023-06-22');
insert into product (id, name, creation_date) values (9, 'Taro Leaves', '2023-06-08');
insert into product (id, name, creation_date) values (10, 'Juice - Tomato, 10 Oz', '2024-03-08');